(() => {
    const G = DracoBits, ctx = G.ctx, C = G.COLORS, B = G.buttons;
    function rating() { G.panel(190, 100, 420, 400); ctx.fillStyle = '#4CAF50'; G.roundRect(325, 145, 150, 150, 18); ctx.fill(); G.centerText('L', 220, 100, '#fff', 'bold'); G.centerText('CLASSIFICAÇÃO INDICATIVA', 340, 25, C.iceWhite, 'bold'); G.centerText('LIVRE', 385, 35, C.success, 'bold'); G.centerText('Não contém conteúdo impróprio.', 435, 18); G.centerText('Aguarde...', 475, 15, C.neonBlue); }
    function menu() { G.centerText('DRACOBITS', 115, 64, C.neonBlue, 'bold'); G.centerText('Cuide. Proteja. Evolua.', 170, 19); G.panel(240, 250, 320, 290); G.button(B.menuPlay); G.button(B.menuHelp, C.softPurple, C.iceWhite); G.button(B.menuCredits, C.backgroundLight, C.iceWhite, C.neonBlue); G.centerText('Núcleo Arcadia // Sistema instável', 570, 14, 'rgba(234,247,255,.7)'); }
    function help() { G.centerText('COMO JOGAR', 65, 36, C.neonBlue, 'bold'); G.panel(75, 100, 650, 385); G.centerText('OBJETIVO', 140, 22, C.coral, 'bold'); G.centerText('Mantenha Draco saudável e restaure o núcleo até 100%.', 175, 16); G.centerText('AÇÕES', 225, 22, C.coral, 'bold'); ['ALIMENTAR — recupera fome.', 'LIMPAR — recupera higiene.', 'BRINCAR — recupera felicidade e gasta energia.', 'DORMIR — recupera energia, mas aumenta a fome.'].forEach((t, i) => G.centerText(t, 260 + i * 32, 16)); G.centerText('Clique nos fragmentos antes que desapareçam.', 405, 16, C.warning); G.button(B.back, C.softPurple, C.iceWhite); }
    function credits() { G.centerText('CRÉDITOS', 80, 38, C.neonBlue, 'bold'); G.panel(120, 125, 560, 350); G.centerText('DESIGN E DESENVOLVIMENTO', 180, 20, C.coral, 'bold'); G.centerText('Camille Silva', 220, 22); G.centerText('Yuri Lima', 252, 22); G.centerText('PROJETO ACADÊMICO', 320, 20, C.coral, 'bold'); G.centerText('Design e Desenvolvimento de Jogos', 360, 18); G.centerText('Universidade Federal de Ouro Preto', 395, 17); G.centerText('2026', 435, 17, C.neonBlue); G.button(B.back, C.softPurple, C.iceWhite); }
    function tutorial() { const m = G.tutorial[G.state.tutorialPage]; G.centerText('TRANSMISSÃO DE ECHO', 75, 34, C.neonBlue, 'bold'); G.panel(85, 125, 630, 330); ctx.strokeStyle = C.softPurple; ctx.lineWidth = 4; ctx.beginPath(); ctx.arc(170, 285, 60, 0, Math.PI * 2); ctx.stroke(); ctx.fillStyle = 'rgba(123,109,204,.25)'; ctx.beginPath(); ctx.arc(170, 285, 48, 0, Math.PI * 2); ctx.fill(); ctx.fillStyle = C.neonBlue; ctx.fillRect(146, 270, 12, 12); ctx.fillRect(182, 270, 12, 12); ctx.fillStyle = C.coral; ctx.font = 'bold 20px Courier New'; ctx.fillText(m.title, 270, 205); m.lines.forEach((line, i) => { ctx.fillStyle = C.iceWhite; ctx.font = '17px Courier New'; ctx.fillText(line, 270, 255 + i * 42); }); B.tutorialNext.label = G.state.tutorialPage === G.tutorial.length - 1 ? 'INICIAR DEMO' : 'CONTINUAR'; G.button(B.tutorialNext, C.softPurple, C.iceWhite); G.centerText(`${G.state.tutorialPage + 1} / ${G.tutorial.length}`, 555, 14, 'rgba(234,247,255,.7)'); }
    function endScreen(victory) { ctx.fillStyle = victory ? 'rgba(20,80,70,.75)' : 'rgba(90,5,15,.82)'; ctx.fillRect(0, 0, G.WIDTH, G.HEIGHT); G.panel(90, 85, 620, 430); G.centerText(victory ? 'NÚCLEO RESTAURADO' : 'COLAPSO DO SISTEMA', 165, 40, victory ? C.success : C.coral, 'bold'); G.centerText(victory ? 'Draco estabilizou o Núcleo Arcadia.' : 'Uma necessidade de Draco permaneceu em zero.', 245, 18); G.centerText(victory ? 'O vínculo entre vocês salvou este mundo.' : 'O sistema não resistiu à instabilidade.', 300, 19, C.neonBlue, 'bold'); G.centerText(victory ? 'DEMO CONCLUÍDA' : 'TENTE NOVAMENTE', 370, 24, C.coral, 'bold'); G.button(B.restart, victory ? C.success : C.coral, C.darkText); G.button(B.endMenu, C.backgroundLight, C.iceWhite, C.neonBlue); }
    function gameplay(now) { const shake = G.state.shake; ctx.save(); if (shake > .5) ctx.translate(G.random(-shake, shake), G.random(-shake, shake)); G.drawWorld(now); G.drawHUD(); G.drawFragment(now); G.drawDraco(now); G.drawDanger(now); G.drawEcho(now); G.drawFeedback(now); G.centerText('DRACO // GUARDIÃO DIGITAL', 290, 18, C.neonBlue, 'bold'); G.button(B.feed); G.button(B.clean); G.button(B.play, C.softPurple, C.iceWhite); G.button(B.sleep, C.backgroundLight, C.iceWhite, C.neonBlue); ctx.restore(); }
    function update(now) { G.updateParticles(); G.updateGameplay(now); G.updateDraco(now); if (G.state.screen === G.STATES.RATING && now - G.state.ratingStartedAt >= G.constants.ratingDuration) G.state.screen = G.STATES.MENU; }
    function draw(now) { G.drawBase(); const s = G.state.screen; if (s === G.STATES.RATING) rating(); else if (s === G.STATES.MENU) menu(); else if (s === G.STATES.HELP) help(); else if (s === G.STATES.CREDITS) credits(); else if (s === G.STATES.TUTORIAL) tutorial(); else if (s === G.STATES.PLAYING) gameplay(now); else if (s === G.STATES.GAME_OVER) endScreen(false); else if (s === G.STATES.VICTORY) endScreen(true); }
    G.canvas.addEventListener('mousedown', event => {
        const rect = G.canvas.getBoundingClientRect(), x = (event.clientX - rect.left) * G.WIDTH / rect.width, y = (event.clientY - rect.top) * G.HEIGHT / rect.height, s = G.state.screen;
        if (s === G.STATES.MENU) { if (G.pointIn(x, y, B.menuPlay)) { G.state.tutorialPage = 0; G.state.screen = G.STATES.TUTORIAL; } else if (G.pointIn(x, y, B.menuHelp)) G.state.screen = G.STATES.HELP; else if (G.pointIn(x, y, B.menuCredits)) G.state.screen = G.STATES.CREDITS; return; }
        if (s === G.STATES.HELP || s === G.STATES.CREDITS) { if (G.pointIn(x, y, B.back)) G.state.screen = G.STATES.MENU; return; }
        if (s === G.STATES.TUTORIAL) { if (G.pointIn(x, y, B.tutorialNext)) { if (G.state.tutorialPage < G.tutorial.length - 1) G.state.tutorialPage++; else G.resetGame(); } return; }
        if (s === G.STATES.PLAYING) { const now = performance.now(); if (G.hitFragment(x, y)) G.resolveFragment(now); else if (G.pointIn(x, y, B.feed)) G.performAction('feed'); else if (G.pointIn(x, y, B.clean)) G.performAction('clean'); else if (G.pointIn(x, y, B.play)) G.performAction('play'); else if (G.pointIn(x, y, B.sleep)) G.performAction('sleep'); return; }
        if (s === G.STATES.GAME_OVER || s === G.STATES.VICTORY) { if (G.pointIn(x, y, B.restart)) { G.state.tutorialPage = 0; G.state.screen = G.STATES.TUTORIAL; } else if (G.pointIn(x, y, B.endMenu)) G.state.screen = G.STATES.MENU; }
    });
    function loop(now) { update(now); draw(now); requestAnimationFrame(loop); }
    requestAnimationFrame(loop);
})();
